/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ThermostatInfo.xml -a ThermostatInfoAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ThermostatInfoAdapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ThermostatAdaptor
 */

ThermostatAdaptor::ThermostatAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ThermostatAdaptor::~ThermostatAdaptor()
{
    // destructor
}

bool ThermostatAdaptor::coolingOn() const
{
    // get the value of property coolingOn
    return qvariant_cast< bool >(parent()->property("coolingOn"));
}

double ThermostatAdaptor::currentTemp() const
{
    // get the value of property currentTemp
    return qvariant_cast< double >(parent()->property("currentTemp"));
}

bool ThermostatAdaptor::fanOn() const
{
    // get the value of property fanOn
    return qvariant_cast< bool >(parent()->property("fanOn"));
}

bool ThermostatAdaptor::heatingOn() const
{
    // get the value of property heatingOn
    return qvariant_cast< bool >(parent()->property("heatingOn"));
}

double ThermostatAdaptor::maxTemp() const
{
    // get the value of property maxTemp
    return qvariant_cast< double >(parent()->property("maxTemp"));
}

double ThermostatAdaptor::minTemp() const
{
    // get the value of property minTemp
    return qvariant_cast< double >(parent()->property("minTemp"));
}

void ThermostatAdaptor::setMaxTemp(double maxTemp)
{
    // handle method call com.packt.bigproject.thermostat.setMaxTemp
    QMetaObject::invokeMethod(parent(), "setMaxTemp", Q_ARG(double, maxTemp));
}

void ThermostatAdaptor::setMinTemp(double minTemp)
{
    // handle method call com.packt.bigproject.thermostat.setMinTemp
    QMetaObject::invokeMethod(parent(), "setMinTemp", Q_ARG(double, minTemp));
}

