/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ThermostatInfo.xml -a ThermostatInfoAdapter
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef THERMOSTATINFOADAPTER_H
#define THERMOSTATINFOADAPTER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.packt.bigproject.thermostat
 */
class ThermostatAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.packt.bigproject.thermostat")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.packt.bigproject.thermostat\">\n"
"    <property access=\"read\" type=\"b\" name=\"fanOn\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"heatingOn\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"coolingOn\"/>\n"
"    <property access=\"read\" type=\"d\" name=\"currentTemp\"/>\n"
"    <property access=\"read\" type=\"d\" name=\"minTemp\"/>\n"
"    <property access=\"read\" type=\"d\" name=\"maxTemp\"/>\n"
"    <signal name=\"fanOnChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"val\"/>\n"
"    </signal>\n"
"    <signal name=\"heatingOnChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"val\"/>\n"
"    </signal>\n"
"    <signal name=\"coolingOnChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"val\"/>\n"
"    </signal>\n"
"    <signal name=\"currentTempChanged\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"val\"/>\n"
"    </signal>\n"
"    <signal name=\"minTempChanged\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"val\"/>\n"
"    </signal>\n"
"    <signal name=\"maxTempChanged\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"val\"/>\n"
"    </signal>\n"
"    <method name=\"setMinTemp\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"minTemp\"/>\n"
"    </method>\n"
"    <method name=\"setMaxTemp\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"maxTemp\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ThermostatAdaptor(QObject *parent);
    virtual ~ThermostatAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool coolingOn READ coolingOn)
    bool coolingOn() const;

    Q_PROPERTY(double currentTemp READ currentTemp)
    double currentTemp() const;

    Q_PROPERTY(bool fanOn READ fanOn)
    bool fanOn() const;

    Q_PROPERTY(bool heatingOn READ heatingOn)
    bool heatingOn() const;

    Q_PROPERTY(double maxTemp READ maxTemp)
    double maxTemp() const;

    Q_PROPERTY(double minTemp READ minTemp)
    double minTemp() const;

public Q_SLOTS: // METHODS
    void setMaxTemp(double maxTemp);
    void setMinTemp(double minTemp);
Q_SIGNALS: // SIGNALS
    void coolingOnChanged(bool val);
    void currentTempChanged(double val);
    void fanOnChanged(bool val);
    void heatingOnChanged(bool val);
    void maxTempChanged(double val);
    void minTempChanged(double val);
};

#endif
